# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'A' do

    pod 'PinterestLayout'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'SideMenu'

end
